#!/usr/bin/env bash
#
# Stamp the workspace version from the release tag.
#
# Releases are triggered by pushing a version tag and nothing else -- Cargo.toml
# is deliberately NOT bumped by hand. cargo-dist refuses to release when the tag
# and the workspace version disagree ("This workspace doesn't have anything for
# dist to Release!"), so every job that runs a dist command stamps the version
# from the tag first. This also keeps `phpxray --version` honest: the version is
# compiled into the binary from Cargo.toml, so overriding it only inside dist
# (via --force-tag) would ship a binary that misreports itself.
#
# The rewrite is purely textual so it works offline and inside the musl build
# containers, where no cargo registry is warm.
#
# release.yml is autogenerated by `dist init`. If you regenerate it, re-add the
# "Stamp the workspace version from the tag" step to the plan, build-local,
# build-global and host jobs. Only those four call sites are lost, not this logic.
set -euo pipefail

tag="${1:?usage: stamp-version.sh <tag>}"
version="${tag#v}"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
  echo "error: tag '$tag' does not carry a major.minor.patch version" >&2
  exit 1
fi

python3 - "$version" <<'PY'
import re
import sys
from pathlib import Path

version = sys.argv[1]
manifest = Path("Cargo.toml")
src = manifest.read_text(encoding="utf-8")


def stamp_workspace_version(text: str) -> str:
    """Set the `version` under [workspace.package]; members inherit it."""
    out = []
    section = None
    stamped = False
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("["):
            section = stripped
        elif section == "[workspace.package]" and not stamped and re.match(r"version\s*=", stripped):
            line = f'version = "{version}"\n'
            stamped = True
        out.append(line)
    if not stamped:
        sys.exit("error: could not locate the version under [workspace.package] in Cargo.toml")
    return "".join(out)


def member_crate_names(text: str) -> list[str]:
    """Crate names of every workspace member, read from their own manifests."""
    block = re.search(r"members\s*=\s*\[(.*?)\]", text, re.DOTALL)
    if not block:
        return []
    names = []
    for path in re.findall(r'"([^"]+)"', block.group(1)):
        member = Path(path) / "Cargo.toml"
        if not member.is_file():
            continue
        name = re.search(
            r'^\s*name\s*=\s*"([^"]+)"', member.read_text(encoding="utf-8"), re.MULTILINE
        )
        if name:
            names.append(name.group(1))
    return names


def stamp_lockfile(members: list[str]) -> None:
    """Stamp member versions in Cargo.lock so a --locked build still resolves."""
    lock = Path("Cargo.lock")
    if not lock.is_file() or not members:
        return
    wanted = set(members)

    def stamp_package(match: re.Match) -> str:
        block = match.group(0)
        name = re.search(r'^name = "([^"]+)"$', block, re.MULTILINE)
        if not name or name.group(1) not in wanted:
            return block
        return re.sub(
            r'^version = "[^"]*"$', f'version = "{version}"', block, count=1, flags=re.MULTILINE
        )

    text = re.sub(
        r"\[\[package\]\]\n(?:[^\n]+\n)+", stamp_package, lock.read_text(encoding="utf-8")
    )
    lock.write_text(text, encoding="utf-8")


members = member_crate_names(src)
manifest.write_text(stamp_workspace_version(src), encoding="utf-8")
stamp_lockfile(members)

print(f"stamped workspace version = {version} across {len(members)} member(s)")
PY
