<?php
/**
 * Emit a manifest of PHP's built-in symbol *names* — functions, class-likes, and
 * constants — for the analyzer's existence checks (unknown-symbol detection).
 *
 * Only NAMES are captured: they are version-stable. Signatures/types are NOT,
 * so they come from version-aware stubs (phpstorm-stubs) at the type-system
 * stage, never from a single-version snapshot like this.
 *
 * Run via `xtask gen-stubs`; the committed output is read by `php-index`. CI
 * never runs PHP.
 */

error_reporting(E_ALL & ~E_DEPRECATED);

$out = [];
$out[] = "# Built-in symbol names from " . PHP_VERSION . " — existence only.";
$out[] = "# Generated by `xtask gen-stubs`; do not edit. Names are version-stable;";
$out[] = "# signatures/types are not and come from version-aware stubs later.";

$section = function (string $name, array $items) use (&$out) {
    sort($items, SORT_STRING);
    $items = array_values(array_unique($items));
    $out[] = "[$name]";
    foreach ($items as $i) {
        $out[] = $i;
    }
};

// Internal functions.
$section('functions', get_defined_functions()['internal']);

// Class-likes, split by kind (internal only).
$classes = $interfaces = $traits = $enums = [];
foreach (get_declared_classes() as $c) {
    $r = new ReflectionClass($c);
    if (!$r->isInternal()) {
        continue;
    }
    if (method_exists($r, 'isEnum') && $r->isEnum()) {
        $enums[] = $c;
    } else {
        $classes[] = $c;
    }
}
foreach (get_declared_interfaces() as $i) {
    if ((new ReflectionClass($i))->isInternal()) {
        $interfaces[] = $i;
    }
}
foreach (get_declared_traits() as $t) {
    if ((new ReflectionClass($t))->isInternal()) {
        $traits[] = $t;
    }
}
$section('classes', $classes);
$section('interfaces', $interfaces);
$section('traits', $traits);
$section('enums', $enums);

// Global constants (everything defined in this clean script is built-in).
$section('constants', array_keys(get_defined_constants()));

echo implode("\n", $out), "\n";
