[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "xtask"
path = "src/lib.rs"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
php-span.workspace = true
php-intern.workspace = true
php-ast.workspace = true
php-lexer.workspace = true
php-parser.workspace = true
php-resolve.workspace = true
php-index.workspace = true
php-phpdoc.workspace = true
walkdir.workspace = true
