[package]
name = "php-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "php_cli"
path = "src/lib.rs"

[[bin]]
name = "php-analyzer"
path = "src/main.rs"

[dependencies]
php-span.workspace = true
php-diagnostics.workspace = true
php-parser.workspace = true
php-resolve.workspace = true
php-index.workspace = true
php-reflect.workspace = true
php-rules.workspace = true
php-config.workspace = true
walkdir.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
regex.workspace = true
