//! Cap #4: typed built-in **function** signatures, loaded from a committed
//! manifest (`stubs/builtin-functions.txt`, generated by `xtask gen-stubs` from
//! the phpstorm-stubs submodule and keyed to our target PHP version).
//!
//! Each line is `fqn<TAB>return<TAB>p1;p2;…` where a param is `name#type#flags`
//! (flags ⊆ `r`=by-ref `v`=variadic `o`=optional; empty type ⇒ `mixed`). Types
//! are `php_types::Type` Display, re-parsed here via the PHPDoc type grammar so
//! the manifest stays human-readable and we reuse one type parser. Parsing is
//! lenient — an unrecognised type string falls back to `mixed`.

use crate::{resolve_doc_type, FunctionReflection, ParamReflection};
use php_resolve::Scope;
use php_types::Type;

const BUILTIN_FUNCTIONS: &str = include_str!("../stubs/builtin-functions.txt");

/// Parse the committed manifest into function reflections.
pub(crate) fn builtin_functions() -> Vec<FunctionReflection> {
    let scope = Scope::global();
    BUILTIN_FUNCTIONS.lines().filter_map(|line| parse_line(line, &scope)).collect()
}

fn parse_line(line: &str, scope: &Scope) -> Option<FunctionReflection> {
    if line.is_empty() || line.starts_with('#') {
        return None;
    }
    let mut fields = line.split('\t');
    let fqn = fields.next()?.to_string();
    let return_type = deser_type(fields.next().unwrap_or(""), scope);
    let params_field = fields.next().unwrap_or("");
    let params = if params_field.is_empty() {
        Vec::new()
    } else {
        params_field.split(';').filter_map(|p| parse_param(p, scope)).collect()
    };
    Some(FunctionReflection {
        fqn,
        params,
        return_type,
        by_ref: false,
        templates: Vec::new(),
        deprecated: false,
        builtin: true,
    })
}

fn parse_param(s: &str, scope: &Scope) -> Option<ParamReflection> {
    let mut f = s.split('#');
    let name = f.next()?.to_string();
    let ty = deser_type(f.next().unwrap_or(""), scope);
    let flags = f.next().unwrap_or("");
    Some(ParamReflection {
        name,
        ty,
        by_ref: flags.contains('r'),
        variadic: flags.contains('v'),
        optional: flags.contains('o'),
        promoted: false,
    })
}

fn deser_type(s: &str, scope: &Scope) -> Type {
    if s.is_empty() {
        return Type::Mixed;
    }
    match php_phpdoc::parse_type(s) {
        Some(dt) => resolve_doc_type(scope, &[], &dt),
        None => Type::Mixed,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_and_resolves_common_signatures() {
        let fns = builtin_functions();
        assert!(fns.len() > 4000, "expected thousands of builtins, got {}", fns.len());

        let strlen = fns.iter().find(|f| f.fqn.eq_ignore_ascii_case("strlen")).unwrap();
        assert_eq!(strlen.return_type, Type::Int);
        assert_eq!(strlen.params.len(), 1);
        assert_eq!(strlen.params[0].ty, Type::String);

        let count = fns.iter().find(|f| f.fqn.eq_ignore_ascii_case("count")).unwrap();
        assert_eq!(count.return_type, Type::Int);
        // mode param is optional.
        assert!(count.params.last().unwrap().optional);
    }
}
