//! Cap #4: typed built-in **function** signatures, loaded from a committed
//! manifests (`stubs/builtin-functions-*.txt`, generated by `xtask gen-stubs`
//! from the phpstorm-stubs submodule and keyed to the target PHP version).
//!
//! Each line is `fqn<TAB>return<TAB>p1;p2;…` where a param is `name#type#flags`
//! (flags ⊆ `r`=by-ref `v`=variadic `o`=optional; empty type ⇒ `mixed`). Types
//! are `php_types::Type` Display, re-parsed here via the PHPDoc type grammar so
//! the manifest stays human-readable and we reuse one type parser. Parsing is
//! lenient — an unrecognised type string falls back to `mixed`.

use crate::{
    resolve_doc_type, AttributeSpec, ClassReflection, ConstReflection, FunctionReflection,
    MethodReflection, ParamReflection, PropertyReflection,
};
use php_ast::{ClassKind, Visibility};
use php_resolve::Scope;
use php_types::{PhpVersion, Type};

const BUILTIN_FUNCTIONS_80400: &str = include_str!("../stubs/builtin-functions-80400.txt");
const BUILTIN_FUNCTIONS_80500: &str = include_str!("../stubs/builtin-functions-80500.txt");
const BUILTIN_FUNCTIONS_80600: &str = include_str!("../stubs/builtin-functions-80600.txt");
const BUILTIN_CLASSES_80400: &str = include_str!("../stubs/builtin-classes-80400.txt");
const BUILTIN_CLASSES_80500: &str = include_str!("../stubs/builtin-classes-80500.txt");
const BUILTIN_CLASSES_80600: &str = include_str!("../stubs/builtin-classes-80600.txt");

/// Parse the committed manifest into function reflections for `version`.
pub(crate) fn builtin_functions_for(version: PhpVersion) -> Vec<FunctionReflection> {
    let scope = Scope::global();
    select_manifests(version)
        .0
        .lines()
        .filter_map(|line| parse_line(line, &scope))
        .collect()
}

/// Parse the committed built-in class-member manifest for `version`.
pub(crate) fn builtin_classes_for(version: PhpVersion) -> Vec<ClassReflection> {
    let scope = Scope::global();
    let mut classes = Vec::<ClassReflection>::new();
    for line in select_manifests(version).1.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut fields = line.split('\t');
        match fields.next() {
            Some("class") => {
                let kind = parse_kind(fields.next().unwrap_or("class"));
                let fqn = fields.next().unwrap_or("").to_string();
                if fqn.is_empty() {
                    continue;
                }
                let parents = parse_named_list(fields.next().unwrap_or(""));
                let interfaces = parse_named_list(fields.next().unwrap_or(""));
                let traits = parse_named_list(fields.next().unwrap_or(""));
                let flags = fields.next().unwrap_or("");
                classes.push(ClassReflection {
                    fqn,
                    kind,
                    is_abstract: flags.contains('a'),
                    is_final: flags.contains('f'),
                    is_readonly: flags.contains('r'),
                    parents,
                    interfaces,
                    traits,
                    templates: Vec::new(),
                    methods: Vec::new(),
                    properties: Vec::new(),
                    constants: Vec::new(),
                    mixins: Vec::new(),
                    deprecated: false,
                    attribute: builtin_attribute(flags),
                    consistent_constructor: false,
                    builtin: true,
                });
            }
            Some("method") => {
                let class = fields.next().unwrap_or("");
                let name = fields.next().unwrap_or("");
                let visibility = parse_visibility(fields.next().unwrap_or("public"));
                let flags = fields.next().unwrap_or("");
                let return_type = deser_type(fields.next().unwrap_or(""), &scope);
                let native_return = deser_type(fields.next().unwrap_or(""), &scope);
                let params = parse_params_field(fields.next().unwrap_or(""), &scope);
                let Some(cr) = ensure_class(&mut classes, class) else {
                    continue;
                };
                cr.methods.push(MethodReflection {
                    name: name.to_string(),
                    visibility,
                    is_static: flags.contains('s'),
                    is_abstract: flags.contains('a'),
                    is_final: flags.contains('f'),
                    params,
                    return_type,
                    explicit_return: true,
                    native_return,
                    templates: Vec::new(),
                    deprecated: false,
                    pure: flags.contains('p'),
                    must_use_return_value: flags.contains('u'),
                    magic: false,
                });
            }
            Some("property") => {
                let class = fields.next().unwrap_or("");
                let name = fields.next().unwrap_or("");
                let visibility = parse_visibility(fields.next().unwrap_or("public"));
                let flags = fields.next().unwrap_or("");
                let ty = deser_type(fields.next().unwrap_or(""), &scope);
                let native_ty = deser_type(fields.next().unwrap_or(""), &scope);
                let Some(cr) = ensure_class(&mut classes, class) else {
                    continue;
                };
                cr.properties.push(PropertyReflection {
                    name: name.to_string(),
                    visibility,
                    is_static: flags.contains('s'),
                    is_readonly: flags.contains('r'),
                    ty,
                    native_ty,
                    has_default: false,
                    access: php_phpdoc::PropertyAccess::ReadWrite,
                    magic: false,
                });
            }
            Some("constant") => {
                let class = fields.next().unwrap_or("");
                let name = fields.next().unwrap_or("");
                let visibility = parse_visibility(fields.next().unwrap_or("public"));
                let flags = fields.next().unwrap_or("");
                let ty = deser_type(fields.next().unwrap_or(""), &scope);
                let int_value = fields.next().and_then(|s| {
                    if s.is_empty() {
                        None
                    } else {
                        s.parse::<i64>().ok()
                    }
                });
                let Some(cr) = ensure_class(&mut classes, class) else {
                    continue;
                };
                cr.constants.push(ConstReflection {
                    name: name.to_string(),
                    visibility,
                    ty,
                    is_final: flags.contains('f'),
                    int_value,
                });
            }
            _ => {}
        }
    }
    classes
}

fn select_manifests(version: PhpVersion) -> (&'static str, &'static str) {
    match select_manifest_id(version.id()) {
        80400 => (BUILTIN_FUNCTIONS_80400, BUILTIN_CLASSES_80400),
        80500 => (BUILTIN_FUNCTIONS_80500, BUILTIN_CLASSES_80500),
        _ => (BUILTIN_FUNCTIONS_80600, BUILTIN_CLASSES_80600),
    }
}

fn select_manifest_id(id: u32) -> u32 {
    if id < 80500 {
        80400
    } else if id < 80600 {
        80500
    } else {
        80600
    }
}

fn parse_line(line: &str, scope: &Scope) -> Option<FunctionReflection> {
    if line.is_empty() || line.starts_with('#') {
        return None;
    }
    let mut fields = line.split('\t');
    let fqn = fields.next()?.to_string();
    let return_type = deser_type(fields.next().unwrap_or(""), scope);
    let params_field = fields.next().unwrap_or("");
    let params = if params_field.is_empty() {
        Vec::new()
    } else {
        params_field
            .split(';')
            .filter_map(|p| parse_param(p, scope))
            .collect()
    };
    Some(FunctionReflection {
        fqn,
        params,
        return_type: return_type.clone(),
        native_return: return_type,
        by_ref: false,
        templates: Vec::new(),
        deprecated: false,
        // Built-in purity is curated separately (rules' PURE_BUILTINS); the stub
        // manifest carries no purity info.
        pure: false,
        must_use_return_value: false,
        builtin: true,
    })
}

fn parse_param(s: &str, scope: &Scope) -> Option<ParamReflection> {
    let mut f = s.split('#');
    let name = f.next()?.to_string();
    let ty = deser_type(f.next().unwrap_or(""), scope);
    let flags = f.next().unwrap_or("");
    Some(ParamReflection {
        name,
        native_ty: ty.clone(),
        ty,
        by_ref: flags.contains('r'),
        variadic: flags.contains('v'),
        optional: flags.contains('o'),
        promoted: false,
        explicit: true,
    })
}

fn parse_params_field(s: &str, scope: &Scope) -> Vec<ParamReflection> {
    if s.is_empty() {
        Vec::new()
    } else {
        s.split(';').filter_map(|p| parse_param(p, scope)).collect()
    }
}

fn deser_type(s: &str, scope: &Scope) -> Type {
    if s.is_empty() {
        return Type::Mixed;
    }
    match php_phpdoc::parse_type(s) {
        Some(dt) => resolve_doc_type(scope, &[], &dt),
        None => Type::Mixed,
    }
}

fn parse_kind(s: &str) -> ClassKind {
    match s {
        "interface" => ClassKind::Interface,
        "trait" => ClassKind::Trait,
        "enum" => ClassKind::Enum,
        _ => ClassKind::Class,
    }
}

fn parse_visibility(s: &str) -> Visibility {
    match s {
        "private" => Visibility::Private,
        "protected" => Visibility::Protected,
        _ => Visibility::Public,
    }
}

fn parse_named_list(s: &str) -> Vec<Type> {
    s.split(',')
        .filter(|p| !p.is_empty())
        .map(|fqn| Type::Named {
            fqn: fqn.to_string(),
            args: Vec::new(),
        })
        .collect()
}

fn ensure_class<'a>(
    classes: &'a mut Vec<ClassReflection>,
    fqn: &str,
) -> Option<&'a mut ClassReflection> {
    if fqn.is_empty() {
        return None;
    }
    if let Some(idx) = classes.iter().position(|c| c.fqn.eq_ignore_ascii_case(fqn)) {
        return classes.get_mut(idx);
    }
    classes.push(ClassReflection {
        fqn: fqn.to_string(),
        kind: ClassKind::Class,
        is_abstract: false,
        is_final: false,
        is_readonly: false,
        parents: Vec::new(),
        interfaces: Vec::new(),
        traits: Vec::new(),
        templates: Vec::new(),
        methods: Vec::new(),
        properties: Vec::new(),
        constants: Vec::<ConstReflection>::new(),
        mixins: Vec::new(),
        deprecated: false,
        attribute: None,
        consistent_constructor: false,
        builtin: true,
    });
    classes.last_mut()
}

fn builtin_attribute(flags: &str) -> Option<AttributeSpec> {
    if flags.contains('A') {
        Some(AttributeSpec {
            targets: crate::attr_target::ALL,
            repeatable: false,
        })
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_and_resolves_common_signatures() {
        let fns = builtin_functions_for(PhpVersion::default());
        assert!(
            fns.len() > 4000,
            "expected thousands of builtins, got {}",
            fns.len()
        );

        let strlen = fns
            .iter()
            .find(|f| f.fqn.eq_ignore_ascii_case("strlen"))
            .unwrap();
        assert_eq!(strlen.return_type, Type::Int);
        assert_eq!(strlen.params.len(), 1);
        assert_eq!(strlen.params[0].ty, Type::String);

        let count = fns
            .iter()
            .find(|f| f.fqn.eq_ignore_ascii_case("count"))
            .unwrap();
        assert_eq!(count.return_type, Type::Int);
        // mode param is optional.
        assert!(count.params.last().unwrap().optional);
    }

    #[test]
    fn loads_common_builtin_class_members() {
        let classes = builtin_classes_for(PhpVersion::default());
        let date = classes
            .iter()
            .find(|c| c.fqn.eq_ignore_ascii_case("DateTimeImmutable"))
            .unwrap();
        assert!(date.interfaces.iter().any(|t| {
            matches!(t, Type::Named { fqn, .. } if fqn.eq_ignore_ascii_case("DateTimeInterface"))
        }));
        assert!(date
            .methods
            .iter()
            .any(|m| m.name.eq_ignore_ascii_case("format") && m.return_type == Type::String));

        let zone = classes
            .iter()
            .find(|c| c.fqn.eq_ignore_ascii_case("DateTimeZone"))
            .unwrap();
        assert!(zone
            .methods
            .iter()
            .any(|m| m.name.eq_ignore_ascii_case("getName") && m.return_type == Type::String));
    }
}
